require(RSQLite)
require(tidyr)
require(dplyr)
require(readr)
# require(lubridate)
require(markdown)
require(shiny)
require(DT)
require(vegan)
require(biogeo)
require(sp)
require(rgeos)
require(rgdal)
devtools::install_github("hadley/lubridate")
devtools::install_github("rstudio/leaflet")
