require(RSQLite)
require(tidyr)
require(dplyr)
# require(lubridate)
require(markdown)
require(shiny)
require(DT)
require(vegan)
devtools::install_github("hadley/lubridate")
devtools::install_github("rstudio/leaflet")
